# Generated by Django 3.1 on 2022-05-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('party_address', models.CharField(max_length=50)),
                ('party_pincode', models.IntegerField()),
                ('party_city', models.CharField(max_length=20)),
                ('party_state', models.CharField(max_length=20)),
                ('party_opBal', models.IntegerField()),
            ],
        ),
    ]
