# Generated by Django 4.0.3 on 2022-05-08 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0011_alter_stock_register_id_alter_toldiary_id'),
        ('Ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='id',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='party_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TolDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('bags', models.IntegerField()),
                ('extra', models.IntegerField()),
                ('standardBharti', models.IntegerField()),
                ('date_modified', models.DateField(default=django.utils.timezone.now)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isCredit', models.BooleanField(default=False)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tol.items')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.ledger')),
            ],
        ),
    ]
