# Generated by Django 4.0.3 on 2022-05-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0002_remove_ledger_id_alter_ledger_party_name_toldiary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TolDiary',
            new_name='TolDiaryAdat',
        ),
    ]
