# Generated by Django 4.0.3 on 2022-05-08 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0011_alter_stock_register_id_alter_toldiary_id'),
        ('Ledger', '0003_rename_toldiary_toldiaryadat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isCredit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='toldiaryadat',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tol.items'),
        ),
    ]
