# Generated by Django 3.1 on 2022-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0005_auto_20220604_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='standardBharti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
