# Generated by Django 4.0.3 on 2022-06-18 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0013_alter_stock_register_id_alter_toldiary_id'),
        ('Ledger', '0006_auto_20220604_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toldiaryadat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BillMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('bags', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.IntegerField(default=0)),
                ('standardBharti', models.IntegerField(default=0)),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='BillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateField(default=django.utils.timezone.now)),
                ('billId', models.IntegerField()),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tol.items')),
                ('partyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.ledger')),
            ],
        ),
    ]
