# Generated by Django 4.0.3 on 2022-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0007_alter_entry_id_alter_toldiaryadat_id_billmetadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmap',
            name='id',
        ),
        migrations.AlterField(
            model_name='billmap',
            name='billId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
