# Generated by Django 4.0.3 on 2022-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0008_remove_billmap_id_alter_billmap_billid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='billId',
            field=models.IntegerField(default=0),
        ),
    ]
