# Generated by Django 3.1 on 2022-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0009_entry_billid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toldiaryadat',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='toldiaryadat',
            name='party_name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BillMetaData',
        ),
        migrations.DeleteModel(
            name='TolDiaryAdat',
        ),
    ]
