# Generated by Django 4.0.3 on 2022-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TolDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisan_name', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('bags', models.IntegerField()),
            ],
        ),
    ]
