# Generated by Django 2.2.3 on 2022-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toldiary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
