# Generated by Django 4.0.3 on 2022-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0002_auto_20220402_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mandi_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('krishikalyan_ses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aadat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='toldiary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
