# Generated by Django 4.0.3 on 2022-04-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0003_items_alter_toldiary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tol.items')),
            ],
        ),
    ]
