# Generated by Django 4.0.3 on 2022-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tol', '0006_alter_toldiary_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_register',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stock_register',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stock_register',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
