# Generated by Django 3.1 on 2022-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hsnCode', models.IntegerField(max_length=10, unique=True)),
                ('mandiTax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('krishiKalyanCess', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aadat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
